<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GreetingService.proto

namespace GPBMetadata;

class GreetingService
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
˜
GreetingService.protoGeneratedSources"b
HelloRequest
name (	
userID (
txid (
orderID (
refundAddress (	"!
HelloResponse
greeting (	2^
GreetingServiceK
greeting.GeneratedSources.HelloRequest.GeneratedSources.HelloResponsebproto3'
        , true);

        static::$is_initialized = true;
    }
}

